services:
  web:
    build: .
    ports:
      - "${PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ../couplet/web/dist:/srv/couplet:ro
      - ../topchef/web/dist:/srv/topchef:ro
    networks:
      - default
      - shared
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  caddy_data:
  caddy_config:

networks:
  shared:
    name: shared
    driver: bridge
