services:
  web:
    build: .
    ports:
      - "${PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

volumes:
  caddy_data:
  caddy_config:
